// http://localhost:3000/event/:id

POST http://localhost:3000/event/new
content-type: application/json

{
  "eventType": "haircraft",
  "eventName": "onHair 4 Night",
  "location": {
    "name": "Madame Rossi 2",
    "address": {
      "additionalString": "2nd floor, next to bar",
      "streetName": "Wegbereiter 21",
      "houseNumber": "234a",
      "postCode": "12345",
      "city": "Berlin",
      "country": "Germany"
    }
  },
  "date": {
    "week_day": {
			"from": "Saturday",
			"to": "Saturday"
		},
    "start_datetime": "May 5, 2020, 11:00 AM",
    "end_datetime": "May 5, 2020, 9:00 PM"
  },
  "eventHost": {
    "group": {
      "name": "Barbery X Collective",
      "email": "barberyx@example.org"
    }
  }
}
