// http://localhost:3000/event/:id

PATCH http://localhost:3000/event/5ddf05b0aae918288eee8980
content-type: application/json

{
	"eventHost.user.name.firstName": "Stella",
	"eventHost.user.email": "stella@example.org",
	"date.week_day": "Monday",
	"date.start_datetime": "Dec 29, 2019, 10:00 AM"
}
