// http://localhost:3000/user/new

POST http://localhost:3000/user/new
content-type: application/json

{
	"firstName": "Gordon",
	"lastName": "Subway",
	"email": "gordon@example.org",
	"role": "organizer"
}